digipay/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("",include("accounts.urls")),
    path("kyc/",include("bankaccounts.urls")),
    path("search/",include("transactions.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path
from transactions import transfer
from transactions import payment_request
from transactions import credit_card

app_name = 'transaction'

urlpatterns = [
    path('',transfer.search_user_by_acc_num,name='search'),
    path('amount_transfer/<account_number>/',transfer.amount_transfer,name='amount_transfer'),
    path('amount_transfer_process/<account_number>/', transfer.amount_transfer_process, name='amount_transfer_process'),
    path('transfer_confirmation/<account_number>/<transaction_id>/', transfer.transfer_confirmation, name='transfer_confirmation'),
    path('transfer_process/<account_number>/<transaction_id>/', transfer.transfer_process, name='transfer_process'),
    path('transfer_completed/<account_number>/<transaction_id>/',transfer.transfer_completed,name="transfer_completed"),

    path('payment_request/',payment_request.payment_request, name="payment_request"),
    path('amount_request/<account_number>/<transaction_id>',payment_request.amount_request, name="amount_request"),
    path('amount_confirmation_request/<account_number>/<transaction_id>', payment_request.amount_confirmation_request, name='amount_confirmation_request'),
    path('confirmation_success_request/<account_number>/<transaction_id>', payment_request.confirmation_success_request, name='confirmation_success_request'),

    path('send_confirmation/<account_number>/<transaction_id>',payment_request.send_confirmation, name="send_confirmation"),
    path('send_amount_processing/<account_number>/<transaction_id>', payment_request.send_amount_processing, name='send_amount_processing'),
    path('send_amount_completed/<account_number>/<transaction_id>', payment_request.send_amount_completed, name='send_amount_completed'),

    path('credit_card',credit_card.credit_card,name='credit_card'),
    path('credit_card_bill/<card_id>/',credit_card.credit_card_bill,name="credit_card_bill"),
    path('withdraw_amount/<card_id>/',credit_card.withdraw_amount,name='withdraw_amount'),
    path('credit_card_delete/<card_id>/',credit_card.credit_card_delete,name="credit_card_delete"),

]

templates/payment_request/request_amount.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">

                    <form action="{% url 'transaction:amount_confirmation_request' account.account_number transaction.transaction_id %}" method="POST">
                        {% csrf_token %}
                        <div class="send-banance">
                            <h4>Request amount</h4 >
                            <span class="mdr">Amount</span>
                            <div class="input-area">
                                <input type="text" name="amount" id="amount" placeholder="Amount">
                            </div>
    
                            <p id="new_balance"></p>
                            <p class="text-danger" id="error-div"></p>
                        </div>
                        <!-- Js -->

                        <div class="send-banance pt-0 mt-0">
                            <span class="mdr">Request Description</span>
                            <div class="input-area">
                                <input type="text" name="request" id="request" placeholder="Description">
                            </div>
                        </div>
                        <div class="footer-area mt-40">
                            <button type="submit" style="padding: 10px 30px; border-radius: 10px; background: rgb(98, 0, 255); color: #fff;" class="active">Request</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    {% endblock content %}

templates/payment_request/request_amount_confirmation.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="choose-recipient">
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <!-- <img src="{{ a.user.kyc.image.url }}" alt="image"> -->
                                        <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;"  alt="image">
    
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account.user.kyc.full_name|title }}</p>
                                        <span class="mdr"><b>{{ account.account_number }}</b></span> <br>
                                        <span class="mdr">{{ account.user.email }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h6>Request confirmation</h6>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span>Sender Name</span>
                                        <b>{{transaction.sender}}</b>
                                    </li>
                                    <li>
                                        <span>Reciever Name</span>
                                        <b>{{transaction.receiver}}</b>
                                    </li>
                                    <li>
                                        <span>Reciever Account_number</span>
                                        <b>{{account.account_number}}</b>
                                    </li>
                                    <li>
                                        <span>Fee</span>
                                        <b>Free</b>
                                    </li>
                                    <li>
                                        <span>E-mail of receiver </span>
                                        <b>{{account.user.email}}</b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="footer-area mt-40">
                            <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Next</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->
    
    <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab"
                                        data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer"
                                        aria-selected="true">transfer</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab"
                                        data-bs-target="#success" type="button" role="tab" aria-controls="success"
                                        aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <a href="javascript:void(0)">
                                                <i class="icon-a-left-arrow"></i>
                                                Back
                                            </a>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content">
                                            <h4>Confirm Transfer!</h4>
                                            <p>Enter your pin number below.</p>
                                            <form action="{% url 'transaction:confirmation_success_request' account.account_number transaction.transaction_id %}" method="POST">
                                                {% csrf_token %}
                                                <div class="userInput">
                                                    <input minlength="4" maxlength="4" name="pin-number" type="text">
                                                </div>
                                                <a href="javascript:void(0)">Reset Pin Number?</a>
                                                <button type="submit" class="mt-60 confirm">Confirm</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content text-center pt-120 pb-120">
                                            <h3>Success</h3>
                                            <p>Transfer was completed.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup start -->
{% endblock content %}

templates/payment_request/request_confirmation_success.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3 receive-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Request Payment</h4>
                        <div class="icon-area">
                            <!-- <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon"> -->
                        </div>
                    </div>
                    <div class="request-submitted pb-120 text-center">
                        <div class="top-area">
                            <div class="icon-area">
                                <img src="{% static 'assets1/images/icon/submitted-icon.png' %}" alt="icon">
                            </div>
                            <h3>Sent!</h3>
                            <p>Payment Request <b>{{transaction.transaction_id}}</b> was sent to <b>{{account.user.kyc.full_name}}</b></p>
                            <h5><a href=""><b>View Detail</b></a> | <a href=""><b>Send Another Payment</b></a></h5>
                        </div>
                        <!-- <div class="share-link">
                            <p>Share direct link with your  payer</p>
                            <ul class="d-flex align-items-center justify-content-center">
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/whatsapp.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/skype.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/messenger.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/copy-link.png' %}" alt="icon"></a>
                                </li>
                            </ul>
                        </div> -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->
{% endblock content %}

templates/payment_request/request_payment.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                    <form  class="flex-fill" method="POST">
                        {% csrf_token %}
                        <div class="form-group d-flex align-items-center">
                            <img src="{% static 'assets1/images/icon/search.png' %}" alt="icon">
                            <input type="text" name="account_number" placeholder="Enter Account Number or ID">
                            <button type="submit"><i class="fas fa-angle-right"></i></button>
                        </div>
                    </form>
                    <div class="user-select">
                        {% if query %}
                        {% for a in account %}
                        <div class="single-user">
                            <div class="left d-flex align-items-center">
                                <div class="img-area">
                                    <!-- <img src="{{ a.user.kyc.image.url }}" alt="image"> -->
                                    <img src="{{ a.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;"  alt="image">

                                </div>
                                <div class="text-area">
                                    <p>{{ a.user.kyc.full_name|title }}</p>
                                    <span class="mdr"><b>{{ a.account_number }}</b></span> <br>
                                    <span class="mdr">{{ a.user.email }}</span>
                                </div>
                            </div>
                            <div class="right">
                                <a href="{% url 'transaction:amount_request' data.account_number query.account_number %}">Choose</a>
                            </div>
                        </div>
                        {% empty %}
                        <div>
                            <h4 class="mt-4">Account does not exist</h4>
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->
    {% endblock content %}

templates/payment_request/send_amount_completed.html
<h1>successful</h1>

templates/payment_request/send_completed.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="choose-recipient">
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <!-- <img src="{{ a.user.kyc.image.url }}" alt="image"> -->
                                        <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;"  alt="image">
    
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account.user.kyc.full_name|title }}</p>
                                        <span class="mdr"><b>{{ account.account_number }}</b></span> <br>
                                        <span class="mdr">{{ account.user.email }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h6>Request confirmation</h6>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span>Sender Name</span>
                                        <b>{{transaction.sender}}</b>
                                    </li>
                                    <li>
                                        <span>Reciever Name</span>
                                        <b>{{transaction.receiver}}</b>
                                    </li>
                                    <li>
                                        <span>Reciever Account_number</span>
                                        <b>{{account.account_number}}</b>
                                    </li>
                                    <li>
                                        <span>Fee</span>
                                        <b>Free</b>
                                    </li>
                                    <li>
                                        <span>E-mail of receiver </span>
                                        <b>{{account.user.email}}</b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="footer-area mt-40">
                            <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Next</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->
    
    <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab"
                                        data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer"
                                        aria-selected="true">transfer</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab"
                                        data-bs-target="#success" type="button" role="tab" aria-controls="success"
                                        aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <a href="javascript:void(0)">
                                                <i class="icon-a-left-arrow"></i>
                                                Back
                                            </a>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content">
                                            <h4>Confirm Transfer!</h4>
                                            <p>Enter your pin number below.</p>
                                            <form action="{% url 'transaction:send_amount_completed' account.account_number transaction.transaction_id %}" method="POST">
                                                {% csrf_token %}
                                                <div class="userInput">
                                                    <input minlength="4" maxlength="4" name="pin-number" type="text">
                                                </div>
                                                <a href="javascript:void(0)">Reset Pin Number?</a>
                                                <button type="submit" class="mt-60 confirm">Confirm</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content text-center pt-120 pb-120">
                                            <h3>Success</h3>
                                            <p>Transfer was completed.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup start -->
{% endblock content %}

templates/payment_request/send_confirmation.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">

                    <form action="{% url 'transaction:send_amount_processing' account.account_number transaction.transaction_id %}" method="POST">
                        {% csrf_token %}
                        <div class="send-banance">
                            <span class="mdr">Step 1 of 3</span>
                            <h4>Make Payment</h4 >
                            <span class="mdr">Amount</span>
                            <div class="input-area">
                                <input type="text" name="amount" id="amount" placeholder="Amount">
                            </div>
    
                            <p id="new_balance"></p>
                            <p class="text-danger" id="error-div"></p>
                        </div>
                        <!-- Js -->

                        <div class="send-banance pt-0 mt-0">
                            <span class="mdr">Description</span>
                            <div class="input-area">
                                <input type="text" name="request" id="request" placeholder="Description">
                            </div>
                        </div>
                        <div class="footer-area mt-40">
                            <button type="submit" style="padding: 10px 30px; border-radius: 10px; background: rgb(98, 0, 255); color: #fff;" class="active">Request</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    {% endblock content %}